Models/ErrorViewModel.cs
namespace la_mia_pizzeria_static.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/EserciziRazorController.cs
using la_mia_pizzeria_static.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace la_mia_pizzeria_static.Controllers
{
    public class EserciziRazorController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public EserciziRazorController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using la_mia_pizzeria_static.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace la_mia_pizzeria_static.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PizzaController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace la_mia_pizzeria_static.Controllers
{
    public class PizzaController : Controller
    {
        // GET: PizzaController
        public ActionResult Index()
        {
            return View();
        }

        // GET: PizzaController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: PizzaController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PizzaController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PizzaController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: PizzaController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PizzaController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: PizzaController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/EserciziRazor/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1 class="text-center">Razor Excercise</h1>

<!--
    1. Dichiarare una variabile valorizzandola con il nostro nome.
Dichiarare un'altra variabile valorizzandola con il nostro cognome.
Stampare il nostro nome e cognome all'interno di un tag h2.
2. Creare una funzione che stampa la somma dei numeri che vanno da 1 a n (con n passato come parametro - n incluso)
Stampare dentro uno span il risultato.
3. Contare quante volte la lettera a è presente nalla frase "nel mezzo del cammin di nostra vita" e stampare questo valore in pagina
4. Creare una List<int> di 20 numeri interi (generati random da 1 a 90, 1 e 90 inclusi) e mostrare in pagina solo i numeri compresi tra 20 e 70
5. Stampare in pagina la data e l'ora attuale (usando la classe DateTime) con il formato anno-mese-giorno ore:minuti:secondi
6. Partendo dalla data di oggi (usando la classe DateTime) stampare in pagina
a. la data di 7 giorni fa
b. che giorno della settimana è oggi (il risultato dovrà essere il nome del giorno (Lunedì, Martedì, ...)
c. che giorno della settimana sarà nello stesso giorno e mese di oggi ma tra un anno (il risultato dovrà essere il nome del giorno (Lunedì, Martedì, ...)
-->

@{
    // ex 1
    string name = "Lorenzo";

    // ex 2
    int Sum(int n)
    {
        int total = 0;
        for (int i = 0; i < n; i++)
        {
            total += n;
        }
        return total;
    }

    // ex 3
    string sentence = "nel mezzo del cammin di nostra vita";
    char[] chars = sentence.ToCharArray();

    int count = 0;
    foreach(char character in chars)
    {
        if (character == 'a') count++;
    }

    // ex 4
    List<int> numbers = new List<int>();
    Random rng = new Random();
    for(int i = 0; i < 20; i++)
    {
        numbers.Add(rng.Next(0, 91));
    }


    // ex 6
    DateTime dt = new DateTime();
    dt = DateTime.Now;
    DateTime newdt = dt.AddDays(-7);
    string day = newdt.DayOfWeek.ToString();
    DateTime oneYear = dt.AddDays(365);
    string oneYearDate = oneYear.DayOfWeek.ToString();

}
<div class="container">
    <div>
        <h1>Ex. 1</h1>
        <p>Dichiarare una variabile valorizzandola con il nostro nome.</p>
        <h5>Ciao! Sono @name</h5>
    </div>

    <div>
        <h1>Ex. 2</h1>
        <p>Creare una funzione che stampa la somma dei numeri che vanno da 1 a n (con n passato come parametro - n incluso)
            Stampare dentro uno span il risultato.</p>
        <span>Il parametro passato è 3. Il risultato sarà: @Sum(3)</span>
    </div>

    <div>
        <h1>Ex. 3</h1>
        <p>Contare quante volte la lettera a è presente nalla frase "nel mezzo del cammin di nostra vita" e stampare questo valore in pagina.</p>
        <p>Caratteri "a" contenuti: @count</p>
    </div>

    <div>
        <h1>Ex. 4</h1>
        <p>Creare una List<int> di 20 numeri interi (generati random da 1 a 90, 1 e 90 inclusi) e mostrare in pagina solo i numeri compresi tra 20 e 70.</p>
        @foreach(int number in numbers)
            {
                @if(number >= 20 && number <= 70)
                {
                    <h5>@number</h5>
                }
            }
    </div>

    <div>
        <h1>Ex. 5</h1>
        <p>Stampare in pagina la data e l'ora attuale (usando la classe DateTime) con il formato anno-mese-giorno ore:minuti:secondi.</p>
        <h4>@DateTime.Now.ToString("yyyy/MM/dd"), @DateTime.Now.ToString("HH:mm:ss")</h4>
    </div>

      <div>
        <h1>Ex. 6</h1>
        <p>Partendo dalla data di oggi (usando la classe DateTime) stampare in pagina la data di 7 giorni fa.</p>
        <h4>Sette giorni fa er il: @day - @newdt.ToString("yyyy/MM/dd")</h4>
        <h4>Che giorno della settimana sarà tra un anno: @oneYearDate</h4>
    </div>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="container d-flex justify-content-center">
    <div class="jumbo"></div>
</div>

Views/Pizza/Details.cshtml
@{
    ViewData["Title"] = "PizzaDetail";
}

@{
    PizzaList list = new PizzaList();

    list.GetList();
}

<h1>Dettaglio Pizza</h1>

@foreach(Pizza pizza in list.GetList()){
    @if(pizza.ID == 1){
        <h1>@pizza.Name</h1>
    }
}

Views/Pizza/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

@{
    // List<Pizza> pizzas = new List<Pizza>();

    PizzaList pizzas = new PizzaList();
    List<Pizza> listTemp = new List<Pizza>();

    Pizza quattroFormaggi = new Pizza("Quattro Formaggi", "La Pizza ai quattro formaggi nella cucina italiana è una varietà di pizza che viene condita con quattro tipi di formaggio (mozzarella, fontina, gorgonzola, parmigiano reggiano) sciolti insieme con salsa di pomodoro o senza pomodoro. È popolare in tutto il mondo ed è uno degli elementi iconici dei menu delle pizzerie.", "https://www.schaer.com/sites/default/files/styles/portrait_sm/public/2022-04/SCHAR_PRODOTTI_PIZZA_4FORMAGGI.jpg?h=9b8ecc1b&itok=VibesmY3", 8.50, 1);
    Pizza prosciuttoFunghi = new Pizza("Pizza Prosciutto & Funghi", "Cosa sarebbe l’Italia senza la Dolce Vita, il pizzaiolo senza la pizza, il prosciutto senza i funghi? Esatto: solo una cosa a metà. Ma il pizzaiolo Scär lavora sempre e solo a tutto tondo.Con maestria riunisce gli ingredienti nella pizza Prosciutto e Funghi. E il gusto diventa più rotondo quando la pizza viene assaporata da una cerchia di amici, o in compagnia dei propri cari.", "https://www.schaer.com/sites/default/files/styles/portrait_sm/public/2022-04/SCHAR_PRODOTTI_PIZZA_PROSCIUTTO%26FUNGHI.jpg?h=05b80a3d&itok=ALCKRtgB", 9.80, 2);
    Pizza salame = new Pizza("Pizza Salame", "Una performance da film, o meglio: ogni volta che trascorri la serata con gli amici puoi presentare una generosa pizza al salame! Lei è una star italiana dal carattere amabile e dal gusto rotondo.Il tappeto rosso di pomodoro si stende su un morbido impasto, che lievita con leggerezza e accoglie la miglior mozzarella su una base croccante. Pronta per Oscar, ma anche per… tutti quelli che non si chiamano come la desiderata statuetta!", "https://www.schaer.com/sites/default/files/styles/portrait_sm/public/2022-04/SCHAR_PRODOTTI_PIZZA_SALAME.jpg?h=5793a142&itok=9BfDqSkk", 7.20, 3);
    Pizza veggie = new Pizza("Pizza Veggie", "È vero che il tempo porta valore e che le cose per essere buone hanno bisogno di tempo? Ma chi l’ha detto?! La pizza Veggie è pronta in un attimo per essere gustata e per regalarti un momento di puro sapore mediterraneo.La base è sottile e croccante e farcita con ottima verdura fresca. Morale della favola: ciò che è pronto in un attimo, va gustato a luuungooo!", "https://www.schaer.com/sites/default/files/styles/portrait_sm/public/2022-04/SCHAR_PRODOTTI_PIZZA_VEGGIE.jpg?h=b676d000&itok=Thosm8ob", 10.50, 4);
    Pizza margherita = new Pizza("Pizza Margherita", "La Pizza Margherita - come farne a meno? Niente paura, ci ha pensato Schär: l'ha fatta con la buona pasta madre, senza glutine e con l'olio d'oliva, l'ha farcita con mozzarella filante e pomodoro di primissima qualità, l'ha rifinita con un pizzico d'origano, poi l'ha cotta su pietra e subito congelata.Voi non dovrete fare altro che togliere questa gustosissima bontà italiana dal congelatore, pazientare per 10 minuti per darle il tempo di risvegliarsi dal suo sonno ghiacciato e ripassarla in forno per pochi minuti. Ed ecco la spettacolare entrata della regina delle pizze: gustate tutta la fragranza della Pizza Margherita di Schär!", "https://www.schaer.com/sites/default/files/styles/portrait_sm/public/2022-04/SCHAR_PRODOTTI_PIZZA_MARGHERITA_1.jpg?h=8425f73a&itok=3rQtUfsk", 6.50, 5);
    Pizza margheritaNoLactose = new Pizza("Pizza Margherita Lactose Free", "Se la cliente non solo è Regina, ma si chiama anche Margherita, allora serve un prodotto di prima classe. La Regina Margherita fu colei che già nel XIX secolo fece creare a Napoli il classico italiano nei colori nazionali: la pizza.E oggi Schär vi offre addirittura la versione senza lattosio! Un impasto sottile e croccante cotto nel forno a legna, farcito con mozzarella di prima qualità e ricoperto di salsa di pomodoro e spezie. E come allora anche oggi il basilico aggiunge quel tocco di verde fra il rosso ed il bianco. Un piatto regale!", "https://www.schaer.com/sites/default/files/styles/portrait_sm/public/2022-04/SCHAR_PRODOTTI_PIZZA_MARGHERITA_LF.jpg?h=d7da52bb&itok=4GxchV-l", 6.50, 6);

    pizzas.AddToList(quattroFormaggi);
    pizzas.AddToList(prosciuttoFunghi);
    pizzas.AddToList(salame);
    pizzas.AddToList(veggie);
    pizzas.AddToList(margherita);
    pizzas.AddToList(margheritaNoLactose);

    listTemp.Add(quattroFormaggi);
    listTemp.Add(prosciuttoFunghi);
    listTemp.Add(salame);
    listTemp.Add(veggie);
    listTemp.Add(margherita);
    listTemp.Add(margheritaNoLactose);
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X          +R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <title>Index</title>
</head>
    <body>
            <h1 class="display-4 text-center">Our Pizzas</h1>
        <div class="d-flex flex-wrap">
            <div class="row justify-content-center" style="column-gap:20px; row-gap:20px">
                @foreach(Pizza pizza in listTemp)
                {
                    <div class="card col-3 text-center gx-3">
                        <img style="height:300px" src="@pizza.Image" class="post-image text-center"/>
                        <h2 class="text-danger">@pizza.Name</h2>
                        <p><span class="fw-bold">Description: </span>@pizza.Description</p>
                        <p class="fw-bold">Price: @pizza.Price&euro;</p>
                        <a href="/Pizza/Details/@pizza.ID">See the details</a>
                    </div>
                }
            </div>
        </div>
    </body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pizza Devs</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/la_mia_pizzeria_static.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <div class="navbar-brand col-1"><img src="~/img/pizzalogo.png" class="logo" /></div>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-bewtween">
                    <ul class="navbar-nav col-11">
                        <li class="nav-item mx-3">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">HomePage</a>
                        </li>
                        <li class="nav-item mx-3">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pizza" asp-action="Index">Our Pizze</a>
                        </li>
                        <li class="nav-item mx-3">
                            <a class="nav-link text-dark" asp-area="" asp-controller="EserciziRazor" asp-action="Index">Razor Exercise</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; 2022 - Lorenzo Ariatta - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>